# Generated by Django 5.1.4 on 2025-01-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="id",
        ),
        migrations.AlterField(
            model_name="record",
            name="key",
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
